src/Entity/Corbeille.php
<?php

namespace App\Entity;

use App\Repository\CorbeilleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CorbeilleRepository::class)
 */
class Corbeille implements EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isEnable;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isShowRead;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isShowWrite;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="corbeilles")
     * @ORM\OrderBy({"name" = "ASC"})
     *
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Organisme::class, inversedBy="corbeilles")
     */
    private $organisme;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Rubric", mappedBy="readers")
     * @ORM\JoinTable("rubricreader_corbeille")
     */
    private $rubricReaders;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Rubric", mappedBy="writers")
     * @ORM\JoinTable("rubricwriter_corbeille")
     */
    private $rubricWriters;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\UnderRubric", mappedBy="readers")
     * @ORM\JoinTable("underrubricreader_corbeille")
     */
    private $underrubricReaders;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\UnderRubric", mappedBy="writers")
     * @ORM\JoinTable("underrubricwriter_corbeille")
     */
    private $underrubricWriters;


    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->rubricReaders = new ArrayCollection();
        $this->rubricWriters = new ArrayCollection();
        $this->underrubricReaders = new ArrayCollection();
        $this->underrubricWriters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFullName(): ?string
    {
        return (null !== $this->organisme) ?
            $this->getOrganisme()->getRef().' - '.$this->getName() :
            $this->getName();
    }

    public function getIsEnable(): ?bool
    {
        return $this->isEnable;
    }

    public function setIsEnable(bool $isEnable): self
    {
        $this->isEnable = $isEnable;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsShowRead(): ?bool
    {
        return $this->isShowRead;
    }

    public function setIsShowRead(bool $isShowRead): self
    {
        $this->isShowRead = $isShowRead;

        return $this;
    }

    public function getIsShowWrite(): ?bool
    {
        return $this->isShowWrite;
    }

    public function setIsShowWrite(bool $isShowWrite): self
    {
        $this->isShowWrite = $isShowWrite;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
        }

        return $this;
    }

    public function getOrganisme(): ?Organisme
    {
        return $this->organisme;
    }

    public function setOrganisme(?Organisme $organisme): self
    {
        $this->organisme = $organisme;

        return $this;
    }

    /**
     * @return Collection|Rubric[]
     */
    public function getRubricReaders(): Collection
    {
        return $this->rubricReaders;
    }

    public function addRubricReader(Rubric $rubricReaders): self
    {
        if (!$this->rubricReaders->contains($rubricReaders)) {
            $this->rubricReaders[] = $rubricReaders;
            $rubricReaders->addReader($this);
        }

        return $this;
    }

    public function removeRubricReader(Rubric $rubricReaders): self
    {
        if ($this->rubricReaders->contains($rubricReaders)) {
            $this->rubricReaders->removeElement($rubricReaders);
            $rubricReaders->removeReader($this);
        }

        return $this;
    }

    /**
     * @return Collection|Rubric[]
     */
    public function getRubricWriters(): Collection
    {
        return $this->rubricWriters;
    }

    public function addRubricWriter(Rubric $rubricWriters): self
    {
        if (!$this->rubricWriters->contains($rubricWriters)) {
            $this->rubricWriters[] = $rubricWriters;
            $rubricWriters->addWriter($this);
        }

        return $this;
    }

    public function removeRubricWriter(Rubric $rubricWriters): self
    {
        if ($this->rubricWriters->contains($rubricWriters)) {
            $this->rubricWriters->removeElement($rubricWriters);
            $rubricWriters->removeWriter($this);
        }

        return $this;
    }

    /**
     * @return Collection|UnderRubric[]
     */
    public function getUnderRubricReaders(): Collection
    {
        return $this->underrubricReaders;
    }

    public function addUnderRubricReader(UnderRubric $underrubricReaders): self
    {
        if (!$this->underrubricReaders->contains($underrubricReaders)) {
            $this->underrubricReaders[] = $underrubricReaders;
            $underrubricReaders->addReader($this);
        }

        return $this;
    }

    public function removeUnderRubricReader(UnderRubric $underrubricReaders): self
    {
        if ($this->underrubricReaders->contains($underrubricReaders)) {
            $this->underrubricReaders->removeElement($underrubricReaders);
            $underrubricReaders->removeReader($this);
        }

        return $this;
    }

    /**
     * @return Collection|UnderRubric[]
     */
    public function getUnderRubricWriters(): Collection
    {
        return $this->underrubricWriters;
    }

    public function addUnderRubricWriter(UnderRubric $underrubricWriters): self
    {
        if (!$this->underrubricWriters->contains($underrubricWriters)) {
            $this->underrubricWriters[] = $underrubricWriters;
            $underrubricWriters->addWriter($this);
        }

        return $this;
    }

    public function removeUnderRubricWriter(UnderRubric $underrubricWriters): self
    {
        if ($this->underrubricWriters->contains($underrubricWriters)) {
            $this->underrubricWriters->removeElement($underrubricWriters);
            $underrubricWriters->removeWriter($this);
        }

        return $this;
    }
}

src/Form/Admin/CorbeilleType.php
<?php

namespace App\Form\Admin;

use App\Entity\Corbeille;
use App\Form\AppTypeAbstract;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CorbeilleType extends AppTypeAbstract
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->buildFormGenerique($builder);
        $this->buildFormOrganisme($builder);
    }

    public function buildFormGenerique(FormBuilderInterface $builder): FormBuilderInterface
    {
        $this->buildFormName($builder);
        $this->buildFormIsEnable($builder);
        $this->buildFormContent($builder);
        $this->buildFormUsers($builder);
        $builder
            ->add('isShowRead', CheckboxType::class, [
                self::LABEL => ' ',
                self::REQUIRED => false,
            ])
            ->add('isShowWrite', CheckboxType::class, [
                self::LABEL => ' ',
                self::REQUIRED => false,
            ])
            ;

        return $builder;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Corbeille::class,
        ]);
    }
}

src/Controller/CorbeilleController.php
<?php

namespace App\Controller;

use App\Entity\Corbeille;
use App\Form\Admin\CorbeilleType;
use App\Manager\CorbeilleManager;
use App\Repository\CorbeilleRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class CorbeilleController
 * @package App\Controller
 * @route("/corbeille")
 */
class CorbeilleController extends AbstractGController
{
    public function __construct
    (
        CorbeilleRepository $repository,
        CorbeilleManager $manager
    )
    {
        $this->repository = $repository;
        $this->manager = $manager;
        $this->domaine = 'corbeille';
    }

    /**
     * @Route("/", name="corbeille_list", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function list()
    {
        return $this->listAction();
    }

    /**
     * @Route("/add", name="corbeille_add", methods={"GET","POST"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function add(Request $request)
    {
        return $this->editAction($request, new Corbeille(), CorbeilleType::class,false);
    }

    /**
     * @Route("/{id}", name="corbeille_del", methods={"DELETE"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function delete(Request $request, Corbeille $item)
    {
        return $this->deleteAction($request, $item);
    }

    /**
     * @Route("/{id}", name="corbeille_show", methods={"GET"})
     * @IsGranted("ROLE_USER")
     */
    public function show(Request $request, Corbeille $item)
    {
        return $this->showAction($request, $item);
    }


    /**
     * @Route("/{id}/edit", name="corbeille_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function edit(Request $request, Corbeille $item)
    {
        return $this->editAction($request, $item, CorbeilleType::class);
    }
}

templates/corbeille/_show/_item.html.twig
{% if item is defined %}

    <div class="row justify-content-center">
        <div class="{{ col_1_2 }}">
            {% embed 'widgets/card-widget.html.twig' %}
                {% block card_class %} card-primary card-outline{% endblock %}
                {% block card_body_class %} box-profile{% endblock %}
                {% block card_body %}
                    <h3 class="profile-username text-center">{{ item.name }}</h3>

                    <p class="text-muted text-center">
                        <a href="{{ path('organisme_show',{id:item.organisme.id}) }}">
                            {{ item.organisme.fullName }}
                        </a>
                    </p>

                    <small class="float-right">
                        {% if item.isEnable %}
                            <span class="text-success">Visible</span>
                        {% else %}
                            <span class="text-danger">Masquée</span>
                        {% endif %}
                    </small>
                {% endblock %}
            {% endembed %}

            {% if item.content %}
                {% embed 'widgets/card-widget.html.twig' %}
                    {% block card_body %}
                        {{ item.content |raw }}
                    {% endblock %}
                {% endembed %}
            {% endif %}

            {% embed 'widgets/card-widget.html.twig' %}
                {% block card_title %}Habilitations{% endblock %}
                {% block card_body_class %}p-0{% endblock %}
                {% block card_body %}
                    <div class="list-group list-group-flush dropright">
                        <div class="list-group-item list-group-item-action">
                            {% if item.isShowRead %}
                                <span class="text-success"><i class="fas fa-check"></i> Lecture</span>
                            {% else %}
                                <span class="text-danger"><i class="fas fa-times"></i> Lecture</span>
                            {% endif %}
                        </div>
                        <div class="list-group-item list-group-item-action">
                            {% if item.isShowWrite %}
                                <span class="text-success"><i class="fas fa-check"></i> Ecriture</span>
                            {% else %}
                                <span class="text-danger"><i class="fas fa-times"></i> Ecriture</span>
                            {% endif %}
                        </div>
                    </div>
                {% endblock %}
            {% endembed %}
            {% embed 'widgets/card-widget.html.twig' %}
                {% block card_title %}Utilisateurs{% endblock %}
                {% block card_body %}
                    {% import "macros/user.html.twig" as usr %}
                    {{ usr.vignettes(item.users) }}
                {% endblock %}
            {% endembed %}

            {% if item.rubricReaders |length >0 %}
                {% embed 'widgets/card-widget.html.twig' with {collapsible:true, collapsed:true} %}
                    {% block card_title %}Rubriques en lecture : {{ item.rubricReaders |length }}{% endblock %}
                    {% block card_body %}
                        {% import "macros/rubric.html.twig" as rbc %}
                        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-3">
                            {% for rubric in item.rubricReaders %}
                                <div class="col mb-4">
                                    {{ rbc.vignette(rubric,'admin_rubric_show','thematic_show') }}
                                </div>
                            {% endfor %}
                        </div>

                    {% endblock %}
                {% endembed %}
            {% endif %}
            {% if item.rubricWriters |length >0 %}
                {% embed 'widgets/card-widget.html.twig' with {collapsible:true, collapsed:true} %}
                    {% block card_title %}Rubriques en écriture : {{ item.rubricWriters |length }}{% endblock %}
                    {% block card_body %}
                        {% import "macros/rubric.html.twig" as rbc %}
                        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-3">
                            {% for rubric in item.rubricWriters %}
                                <div class="col mb-4">
                                    {{ rbc.vignette(rubric,'admin_rubric_show','thematic_show') }}
                                </div>
                            {% endfor %}
                        </div>

                    {% endblock %}
                {% endembed %}
            {% endif %}
{% set datas = item.underRubricReaders %}

{% set nbr = datas |length %}

{% if nbr >0 %}
	{% embed 'widgets/card-widget.html.twig' with {collapsible:true, collapsed:true} %}
		{% block card_title %}Sous-rubriques en lecture :
			{{ nbr }}
		{% endblock %}
		{% block card_body %}
			{% import "macros/underrubric.html.twig" as urbc %}
			<div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-3">
				{% for rubric in datas %}
					<div class="col mb-4">
						{{ urbc.vignette(rubric,'admin_underrubric_show','underthematic_show') }}
					</div>
				{% endfor %}
			</div>

		{% endblock %}
	{% endembed %}
{% endif %}
{% set datas = item.underRubricWriters %}

{% set nbr = datas |length %}

{% if nbr >0 %}
	{% embed 'widgets/card-widget.html.twig' with {collapsible:true, collapsed:true} %}
		{% block card_title %}Sous-rubriques en écriture :
			{{ nbr }}
		{% endblock %}
		{% block card_body %}
			{% import "macros/underrubric.html.twig" as urbc %}
			<div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 row-cols-xl-3">
				{% for rubric in datas %}
					<div class="col mb-4">
						{{ urbc.vignette(rubric,'admin_underrubric_show','underthematic_show') }}
					</div>
				{% endfor %}
			</div>

		{% endblock %}
	{% endembed %}
{% endif %}


        </div>
    </div>

{% endif %}